Разметка всех страниц
htmlacademy-adaptive/2075923-cat-energy-27 pull request #2
Opened 2022-12-03 08:59 UTC by PolyTS

2022-12-04 13:28 UTC, pavel-nyukalo requested changes

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +      <div class="main-navigation_wrapper navigation-wrapper">
1. Насчет БЭМ.
Первая ошибка в `main-navigation_wrapper` - пропущено `_`
Вторая не ошибка, но помни, что для каждого БЭМ-блока будут создаваться свои препроцессорные файлы. То есть придется создать и для блока `navigation` - `navigation.scss/less`, и для блока `navigation-wrapper` - `navigation-wrapper.scss/less`. Что немного излишне на мой взгляд. Лучше сделать элементом - `navigation__wrapper`
2. Я бы этот `div` вообще убрал. Можно будет `nav` центрировать

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +        </a>
Адаптивные изображения будут в дальнейшем рассматриваться.

Но ссылку нужно сделать одну (сейчас их три), а потом уже будем манипулировать изображениями

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +            class="visually-hidden">Открыть меню</span></button>
Да, только я бы отформатировал еще. Плюс опять же не забывай про правило "для каждого БЭМ-блока - свой файл". То есть тут придется еще делать файл `navigation-toogle.scss/less`. Возможно имеет смысл сделать его элементом блока `navigation` - `navigation__toogle`

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +        <img class="promo__pic-conteiner--cover" src="img/cat-main-cover.jpeg" width="320" height="302"
Тут если что при построении сеток доработаем, но одна ошибка по БЭМу тут есть - модификатор без модифицируемой сущности `<img class="promo__pic-conteiner--cover">`. В этом случае должно быть `<img class="promo__pic-conteiner promo__pic-conteiner--cover">`. Но в таком случае будет с оберткой пересекаться названия

И в целом, я бы фоном положил эту картинку

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +        <p class="promo__slogan--dark-theme">Занялся собой? Займись котом!</p>
Только опять же тут ошибка по БЭМу - модификатор без модифицируемой сущности. Должно быть `<h3 class="promo__headline promo__headline--dark-theme">`

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +        <!-- считается ли другой размер картинки на других девайсах за модификацию?я добавила модификатор поэтому -->
Думаю что нет, адаптивные картинки мы потом сделаем, и там у нас в зависимости от медиа запроса будут подгружаться разные картинки

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +        <!-- я думаю кнопка переиспользуемый элемент, поэтому я добавила ему класс button где смогу задат общие стили для кнгопок, а так же модификатор состояний(фокус,ховер и тд)про модификатор логи
Да, хорошее решение

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +        <!--что-то не понимаю как реализована серая подложка под блоками.поэтому оберну еще в один див-->
Я бы тут список сделал для семантики, так мы уйдем от дивянки, и серую подложку как раз `li` зададим

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +        <div class="programms__weight-gain">
И вот когда на `li` переделаешь, им бы лучше одинаковый класс задать, чтобы не дублировать стили

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +          <!-- во в ддругих версиях еще есть цифра один.Мы можем это все прописывать в одном модификаторе, или нужно два? -->
Цифру сможем сделать через [`counter`](https://doka.guide/css/css-counters/) в `css`. Но если не захочется делать через `counter` то логически я бы разделил на два модификатора. Одни за счетчик отвечает, другой за картинку

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +        <p class="result-description">Борис сбросил 5 кг за 2 месяца, просто заменив свой обычный корм на Cat Energy
Опять же правило "для каждого блока свой файл". Тут придется создать три разных файла, причем в двух будет описание только для заголовка и описания соответственно. Лучше сделать их элементами блока `result`

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +          </div>
Тут уже другая ошибка по БЭМ - элемент для элемента - `result__item__description-term`

Можно разбить на блок и сделать так (над именованием класса можно подумать)

```html
<dl class="result__list description">
  <div class="description__item">
    <dt class="description__term">Cнижение веса</dt>
    <dd class="description__definition">5 кг</dd>
  </div>
  ...
```

2022-12-04 13:28 UTC, pavel-niukalo commented on source/index.html
> +          <img class="result__pic--resize" src="img/fat-cat.png" width="280" height="256" alt="Кот до.">
1. Размеры изображения будем менять потом - через тег `picture`
2. Та же ошибка про модификатор

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/index.html
> +          <!-- вот не знаю, стоит ли слайдеру задать класс блок, а переключатель сделать его элементом?вроде бы вне слайдера этот переключатель не может существовать.Еще сделала черпез инпут, просто
Можно выносить, можно не выносить в блок. Тут думаю что при построении сеток уже поймешь, как лучше и проще.
Через инпут тоже пойдет

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/index.html
> +          <div class="result__pic-switch-button">
Я бы только кнопкой это сделал

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/index.html
> +            <svg class="result__pic-switch-button--condition" width="40" height="258" viewbox="0 0 40 258" fill="none"
Просто модификатор - нельзя. Надо еще указывать что он модифицирует. Но учти, если здесь прописать `<svg class="result__pic-switch-button result__pic-switch-button--condition"`, то все стили `result__pic-switch-button` применятся и на `svg`, и на `div`

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/index.html
> +        <h3 class="partnership__text partnership-text">приглашаем
Опять же `partnership` и `partnership-text` - два разных блока. Придется создавать два файла. Я думаю `partnership-text` можно удалить и просто стилизовать через `partnership__text`

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/index.html
> +        <iframe class="map__view--pin"
Модификатор без модифицируемой сущности

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/index.html
> +        <!-- надо ли вставить img если карта не прогрузится?если да, то через модификатор? <img class="map__pic--unloaded" src="img/map.jpeg" width="320" height="362" alt="Карта с отметкой"> -->
Надо, но можно просто класс ей `map__pic` задать и все

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/index.html
> +            <li class="social-item">
Опять же - другой блок. Лучше сделать элементом - `social__item`

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +<html class="catalog" lang="ru">
`page` и `catalog` будут иметь одинаковые стили. То есть дублирование. Я бы здесь так же сделал бы `page`

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +        <ul class="catalog-page-navigation__list menu">
Тут те же замечания что на главной + я бы сделал и хедер, и футер на всех страницах с одними классами  - описать в одном месте и на всех страницах он будет одинаковым. Если где-то чуть что отличается, то модификаторами. А так придется дублировать свойства

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +          <!-- таким списком нормально сделать карточку?или сюда лучше подходит dl? -->
Лучше через `ul`, то бишь оставить

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +        <div class="goods__card card">
Только нужно ли нам столько оберток? Я бы пока убрал, потом если что добавили бы

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +              </div>
А вот здесь как раз таки лучше `dl dt dd`

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +                <!-- модификатор для добавления плюсика.для него не описаны состояния в стайлгайде, хотя должнго быть при наведении меняет цвет.вот думаю может его лучше свг вставить тогда? -->
Думаю, можно будет через `opacity` сделать, но тут как хочешь

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +              <a class="card__title-link">
Пока просто имей ввиду, что все стили для товаров (`card`) применятся и к этим элементам. Возможно, придется разделить

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +              </div>
Тут бы тоже `dl dt dd` сделал бы

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/catalog.html
> +    <section class="partnership-catalog">
Тут все те же замечание как на главной

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/form.html
> +<html class="form-page" lang="ru">
Аналогично. Замечания по хедеру и футеру такие же

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/form.html
> +            </li>
Смотри, тут я бы предложил инпуты и лейблы назвать от блока `form` - `form__label` и `form__input`. Объясню почему. Так мы пропишем стили для этих инпутов один раз и потом просто будем навешивать стили. Если оставить как сейчас, то нам придется продублировать стили и для `interview__name`, и для `interview__weight` и тд. Хотя выглядят они все одинаково, и стили наведения и тд тоже будут одинаковыми

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/form.html
> +                <input class="purpuse__input purpuse__input--unshown" type="radio" value="yes" name="lose weght"
А зачем модификатор? Он за что отвечать будет?

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/form.html
> +              <input class="сontact-details__telephone сontact-details__telephone--icon" type="tel"
Тут аналогично, это два одинаковых инпута (за исключением картинки), поэтому их лучше объединить. И в целом им можно будет дать тот же класс `form__input`, который мы уже опишем. А картинки через модификаторы сделаем

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/form.html
> +          <h3 class="comments__title comments__title--decoration">
Тут вот я задумался. В целом у нас все эти заголовки похожи, но поскольку у каждого свой блок, стилизация будет дублироваться

Я бы предложил разбить так

```html
<form class="form">
  ...
  <fieldset class="form__fieldset сontact-details">
    <legend class="form__legend">Контактные данные
      (владельца кота)
    </legend>
    <ul class="сontact-details__list">
      <li class="сontact-details__item">
        <label class="form__label" for="сontact-details-email">E-mail:*</label>
        <input class="form__input form__input--email сontact-details__email--icon" type="email" id="сontact-details-email"
          name="сontact-details-email" placeholder="kuklachev@gmail.com">
      </li>
      <li class="сontact-details__item">
        <label class="form__label" for="сontact-details-telephone">Телефон:*</label>
        <input class="form__input form__input--tel" type="tel" id="сontact-details-telephone" name="сontact-details-telephone" placeholder="8 (960) 900-60-90">
      </li>
    </ul>
  </fieldset>
  <fieldset class="form__fieldset">
    <legend class="form__legend">Комментарий</legend>
    ....
  </fieldset>
  ...
</form>
```

А доразбивать можно будет внутри уже, если надо будет

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/form.html
> +                <!-- тут мы навернео как в дивайсе будем вставлять чекбокс квадратиком и изображением, поэтому нужен модификатор -->
Мы будем от состояния инпута ставить картинку, поэтому модификатор возможно лишний

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/form.html
> +        <button class="form-button button button--condition" type="submit">Отправить заявку</button>
Я бы сделал элементом - `form__button`

2022-12-04 13:28 UTC, pavel-nyukalo commented on source/form.html
> +        <!-- что-то не пойму, нужна обертка сноске? или в обертке позиционирование а в элементе стили? -->
Я бы не давал, возможно максимум бы кнопку и `span` бы обернул в `div`, но опять же при построении сеток это можем сделать

2022-12-06 12:33 UTC, pavel-nyukalo requested changes

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/index.html
> +      <button class="navigation__toogle navigation-toogle--open" type="button"><span class="visually-hidden">Открыть
Тут еще присутствует ошибка по БЭМ - `navigation-toggle--open` является модификатором блока `navigation-toggle`. А у нас тут элемент - `navigation__toggle`. Вот его и нужно модифицировать - `<button class="navigation__toggle navigation__toggle--open" type="button">`

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/index.html
> +        <img class="promo_product-pic" src="img/promo-product.png" width="280" height="270"
Пропущено `_` в `promo_product-pic` -> `promo__product-pic`

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/index.html
> +        <!-- сделала списком -->
Не ошибка, но потом при построении сеток надо будет подумать - нужен ли теперь нам `div programms__conteiner`? Возможно он лишний, и можно будет сетку строить для `ul`

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/index.html
> +          <!-- убрала модификацию, решила что сделаем по твоей рекомендации через counter.их я так поняла прописываем в стилях элемента блока -->
Модификаторы нам еще пригодятся как минимум для разных картинок

![image](https://user-images.githubusercontent.com/52506235/205910426-408de676-d61e-452f-a31f-59472f11f723.png)

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/index.html
> +          <!-- у маеня тут был инпут, ты написал что лучше сделать через кнгопку.Я вернго поняла? -->
Можно через инпут оставить, в целом тоже решение

Про кнопку имел ввиду вот этот `div`, у которого в классе присутствует `button`

![image](https://user-images.githubusercontent.com/52506235/205911159-ec2e6c44-ecfe-4644-9d96-c0bc6e49fbc7.png)

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/index.html
> +            <svg class="result__pic-switch-button pic-switch-button--condition" width="40" height="258"
`pic-switch-button--condition` - модификатор без модифицируемой сущности. Чтобы поправить должно быть `result__pic-switch-button result__pic-switch-button--condition`

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/catalog.html
>  <body class="catalog__body">
Тут должно стать `page__body`

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/catalog.html
> +      <button class="navigation__toogle navigation-toogle--open" type="button"><span class="visually-hidden">Открыть
Тут тоже не забудь поправить

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/catalog.html
> +            <!-- тут возможнго лишним даю класс product-features, но решила оставлю когда до стилизации дойду.пока что-то подсказывает так -->
Хорошее решение

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/form.html
>  <body class="form-page__body">
Тут вот не поправлено, давай сделаем не `form-page` и `form-page__body`, а как и на других страницах `page` и `page__body`

2022-12-06 12:33 UTC, pavel-nyukalo commented on source/index.html
> +      <button class="navigation__toogle navigation-toogle--open" type="button"><span class="visually-hidden">Открыть
Тут еще присутствует ошибка по БЭМ - `navigation-toggle--open` является модификатором блока `navigation-toggle`. А у нас тут элемент - `navigation__toggle`. Вот его и нужно модифицировать - `<button class="navigation__toggle navigation__toggle--open" type="button">`

2022-12-07 06:17 UTC, PolyTS commented on source/index.html
> +        <!-- сделала списком -->
пока оставлю так, снести если что успею

2022-12-07 06:17 UTC, PolyTS commented on source/index.html
> +          <!-- убрала модификацию, решила что сделаем по твоей рекомендации через counter.их я так поняла прописываем в стилях элемента блока -->
вернула

2022-12-07 07:24 UTC, pavel-niukalo approved these changes

2022-12-07 07:24 UTC, merged