стилизация
htmlacademy-adaptive/2075923-cat-energy-27 pull request #3
Opened 2022-12-11 21:07 UTC by PolyTS

2022-12-12 16:09 UTC, pavel-nyukalo requested changes

2022-12-12 16:09 UTC, pavel-niukalo commented on source/catalog.html
> +          width="600" height="450" style="border: 0;" allowfullscreen="" loading="lazy"
Стили карты лучше вынести в css, раньше валидатор ругался на такое

2022-12-12 16:09 UTC, pavel-niukalo commented on source/sass/blocks/catalog/card__button.scss
> +}
Стили для элементов и модификаторов описываются в файле блока.

То бишь, у нас это элемент блока `card` - описываем в `card.scss`. А этот файл удаляем

2022-12-12 16:09 UTC, pavel-niukalo commented on source/sass/blocks/catalog/card__description-list.scss
> +}
Относится ко всем

2022-12-12 16:09 UTC, pavel-niukalo commented on source/sass/blocks/catalog/card__title.scss
> +  font-family: "Oswald", sans-serif;
По [критерию](https://up.htmlacademy.ru/adaptive/27/criteries#b10) нам нужно так же указать веб-безопасный шрифт

2022-12-12 16:09 UTC, pavel-niukalo commented on source/sass/blocks/catalog/extra-goods__title.scss
> +.extra-goods__title {
Относится ко всему - файлы стилей создаем _только_ для БЭМ-блоков

2022-12-12 16:09 UTC, pavel-nyukalo commented on source/sass/blocks/index/main-header.scss
> +// вот я помню что вроде общие стили и позиционирование должно быть в разных блоках по БЭМ.Поэтому все позиционирование отдала этому классу.Верно?
В целом тут как удобней. Критерия на это нет, и тут сугубо как будет проще ориентироваться в коде

2022-12-12 16:09 UTC, pavel-nyukalo commented on source/sass/blocks/index/main-header.scss
> +// margin: 0 auto; надо ли сейчас блоки центрировать по центру?
Думаю, при построении сеток сделаем

2022-12-12 16:09 UTC, pavel-niukalo commented on source/sass/blocks/index/menu__item.scss
> +// так могу вкладывать?
Да, главное чтобы не больше двух уровней вложенности было

2022-12-12 16:09 UTC, pavel-nyukalo commented on source/sass/blocks/index/promo copy.scss
> +.promo {
Дублирующий файл получился

2022-12-12 16:09 UTC, pavel-nyukalo commented on source/sass/fonts.scss
> +  font-style: italic;
Там точно италик?

2022-12-12 16:09 UTC, pavel-nyukalo commented on source/sass/blocks/index/programms__button.scss
> +  // почему элемент не принимает ширину?
Это ссылка, а она по-умолчанию `display: inline` , и поэтому не применяется ширина

2022-12-15 10:41 UTC, pavel-nyukalo requested changes
Не забывай делать `npm run lint`

![image](https://user-images.githubusercontent.com/52506235/207838106-68073357-53f5-4197-a4a8-a259c4d291eb.png)

2022-12-15 10:41 UTC, pavel-nyukalo commented on source/sass/blocks/catalog/card.scss
> +  font-family: "Oswald", sans-serif;
Тут как обсуждали, надо и сюда добавить веб-безопасный шрифт

2022-12-15 10:41 UTC, pavel-nyukalo commented on source/sass/navigation.scss
> +.navigation-list {
В разметке возможно `navigation__list`? Просто `navigation-list` это по сути отдельный БЭМ-блок, и ему надо свой файл

2022-12-15 10:41 UTC, pavel-nyukalo commented on source/sass/partnership.scss
> +.partnership-main__conteiner {
`partnership-main` - отдельный БЭМ-блок

2022-12-15 10:41 UTC, pavel-nyukalo commented on source/sass/visually-hidden.scss
> +.visually-hidden {
Я бы `visually-hidden` положил в `blocks/`, холиварный вопрос, но по сути тоже отдельный блок

2022-12-15 14:42 UTC, PolyTS commented on source/sass/visually-hidden.scss
> +.visually-hidden {
а я посмотрела, что-то у меня вообще блоки как parntnership,footer и тд выпали.все убрала обратно в blocks/

2022-12-15 14:44 UTC, PolyTS commented on source/sass/partnership.scss
> +.partnership-main__conteiner {
вообще убрала partnershop-main__conteiner, partnershop-catalog__conteiner,  partnershop-form__conteiner.не понимаю зачем мне пока эти сущности.дальше может и верну, но по идее это как и с навигацией и футером

2022-12-15 14:44 UTC, PolyTS commented on source/sass/navigation.scss
> +.navigation-list {
да, ты прав.поменяла

2022-12-15 14:47 UTC, PolyTS commented on source/sass/blocks/catalog/card.scss
> +  font-family: "Oswald", sans-serif;
я добавила, но базово со шрифтам разберусь попозже.чет у меня все равно каша

2022-12-16 14:22 UTC, pavel-nyukalo commented on source/sass/blocks/catalog/card.scss
> +  font-family: "Oswald", sans-serif;
Главное не забудь потом добавить

2022-12-16 14:24 UTC, pavel-nyukalo approved these changes

2022-12-16 14:24 UTC, merged