адаптивные сетки
htmlacademy-adaptive/2075923-cat-energy-27 pull request #4
Opened 2022-12-22 16:51 UTC by PolyTS

2022-12-25 13:53 UTC, pavel-nyukalo reviewed
1. Ссылки на главной не нажимаются

2022-12-25 13:53 UTC, pavel-niukalo commented on source/catalog.html
> +            <ul class="quality__list">
Небольшая дивянка получается. У `extra-goods__card-wrapper quality` вообще нет стилей, он нужен?

Можно сразу список стилизовать

2022-12-25 13:53 UTC, pavel-niukalo commented on source/catalog.html
> +          <svg class="footer_logo-pic footer_logo-pic--condition" xmlns="http://www.w3.org/2000/svg" width="27"
Ошибки в написании БЭМ-элементов, надо два нижних подчеркивания

2022-12-25 13:53 UTC, pavel-niukalo commented on source/form.html
> +        </div>˝
\`` лишнее

2022-12-25 13:53 UTC, pavel-niukalo commented on source/form.html
> +          <svg class="footer_logo-pic footer_logo-pic--condition" xmlns="http://www.w3.org/2000/svg" width="27"
Аналогично

2022-12-25 13:53 UTC, pavel-niukalo commented on source/sass/blocks/catalog/card.scss
> +  }
То что не меняется от одного разрешения к другому можно не дублировать. Например, `display: grid` применится на планшете, и останется до след. переопределения. То есть на десктопе так же будет грид, и снова его прописывать нет смысла. Порой так можно очень сильно сократить код

2022-12-25 13:53 UTC, pavel-niukalo commented on source/sass/blocks/catalog/extra-goods.scss
> +// не понимаю почему не срабатывает наложение
Ответ прост

![image](https://user-images.githubusercontent.com/52506235/209468792-7ea63a03-501f-47cd-9a93-4431a7ca34e0.png)

Псевдоэлемент просто не применяется

2022-12-25 13:53 UTC, pavel-nyukalo commented on source/sass/blocks/footer.scss
> +  }
Напишу к футеру, но относится ко всему

Нам не нужно ограничивать те блоки, которые должны тянуться на всю ширину

То бишь смотрим на макет, и вот все что упирается в края макета (выходит за красные линии контента) должно тянуться на всю ширину. Например, открыли сайт не на 768px, а на 900 с чем-то

Фоновый цвет по макету у нас тянется, соответственно, он должен упираться в правый край страницы

Так же, при открытии сайта не на брейкпоинатах - контент должен центрироваться (либо резиниться, но нам достаточно центрировать)

![image](https://user-images.githubusercontent.com/52506235/209468941-00d57d23-3491-476e-ba3d-86e7932cf7a3.png)

2022-12-25 13:53 UTC, pavel-nyukalo commented on source/sass/blocks/index/how-it-works.scss
> +  @media (min-width: 11px) {
`11px`

Полагаю, должно быть 1220?

2022-12-25 13:53 UTC, pavel-nyukalo commented on source/sass/blocks/index/how-it-works.scss
> +    height: 280px;
Добавление новых элементов сломает верстку, лучше указать `min-height` или добиваться похожести за счет паддингов, элементов и тд

2022-12-25 13:53 UTC, pavel-nyukalo commented on source/sass/blocks/index/menu.scss
> +      border-bottom: 2px solid #ffffff;
Меняется только цвет, поэтому можно поменять `border-bottom-color: #ffffff;`

2022-12-25 13:53 UTC, pavel-nyukalo commented on source/sass/blocks/index/programms.scss
> +  font-family: "Oswald", sans-serif;
Не забывай про веб-безопасный шрифт

2022-12-25 13:53 UTC, pavel-nyukalo commented on source/sass/blocks/index/result.scss
> +  }
Для резкого перехода, начальные точки цветов должны совпадать

![image](https://user-images.githubusercontent.com/52506235/209469971-cb54b1aa-f462-4547-a8d0-dffc19f1f72d.png)

![image](https://user-images.githubusercontent.com/52506235/209469976-babe9d0a-14b8-463f-9940-c218d6fa9eb1.png)

Можешь еще поглядеть [примеров](https://doka.guide/css/linear-gradient/)

2022-12-25 13:53 UTC, pavel-nyukalo commented on source/sass/blocks/page.scss
> +  position: absolute;
Не очень понял для чего `body` делать абсолютно спозиционированным?

2022-12-25 13:53 UTC, pavel-nyukalo commented on source/sass/style.scss
> +@import "viewports.scss"
По поводу переменных - не работает по причине того, что они подключены в самом конце

![image](https://user-images.githubusercontent.com/52506235/209470218-56088241-03bc-4c05-8da5-5b01b96f6947.png)

Из SCSS в CSS компилируется сверху вниз. И получается ситуация такая, что ты используешь например `$desktop-width` в `footer.scss`, но до этого момента он еще не знает, что такое `$desktop-width`.

Именно по этой причине мы импортируем шрифты самыми первыми - чтобы была возможность их использовать 

Подключи переменные либо до, либо после шрифтом (не принципиально) и все заработает

2022-12-26 17:09 UTC, PolyTS commented on source/catalog.html
> +            <ul class="quality__list">
я подумаю как убрать.у меня к  quality дальше привязаны стили.получается если убрать этот див, то по БЭМ получается нет блока от которого идут блок элементы
<img width="452" alt="Снимок экрана 2022-12-26 в 20 07 43" src="https://user-images.githubusercontent.com/100072307/209570433-b0ca16df-8624-4b72-b9d8-9e4f641df918.png">

2022-12-26 17:18 UTC, PolyTS commented on source/sass/blocks/catalog/card.scss
> +  }
этот поправлю, остальные буду проверять.

2022-12-26 17:19 UTC, PolyTS commented on source/sass/blocks/catalog/extra-goods.scss
> +// не понимаю почему не срабатывает наложение
нормально ли тут будет сделать через span?

2022-12-26 18:01 UTC, PolyTS commented on source/sass/style.scss
> +@import "viewports.scss"
буду пробовать,спасибо

2022-12-26 18:02 UTC, PolyTS commented on source/sass/blocks/page.scss
> +  position: absolute;
запуталась

2022-12-26 18:06 UTC, PolyTS commented on source/sass/blocks/index/how-it-works.scss
> +    height: 280px;
снесла пока

2022-12-26 18:07 UTC, PolyTS commented on source/sass/blocks/footer.scss
> +  }
я поправила, теперь корректно?

2022-12-27 13:01 UTC, pavel-nyukalo requested changes
Уже лучше, но давай поправим вот какие моменты еще

1. Контент лучше бы центрировать, чтобы на больших экранах не было пустых областей с одной из сторон

![image](https://user-images.githubusercontent.com/52506235/209669802-2324c0c3-f5c6-4ce4-a023-57c34f7c50f7.png)

Плюс по ТЗ у нас зеленая часть должна упираться в самый край (и котик в ней в самый край)

2. Не нажимаются ссылки в навигации на главной странице

3. В каталоге вот такая история появилась

![image](https://user-images.githubusercontent.com/52506235/209670047-7336bc99-92b1-49e3-a3c6-37776482c608.png)

4. В форме тоже скролл появился

![image](https://user-images.githubusercontent.com/52506235/209670078-b1051623-82d8-4682-aebe-4723b3afe55d.png)

2022-12-29 11:59 UTC, pavel-nyukalo approved these changes

2022-12-29 11:59 UTC, merged